// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package qq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exchange struct {
	ExchangeID int32  `json:"exchange_id"`
	Name       string `json:"name"`
}

type Kline struct {
	TickerID   int32            `json:"ticker_id"`
	Resolution int32            `json:"resolution"`
	Starttime  pgtype.Timestamp `json:"starttime"`
	Open       float64          `json:"open"`
	High       float64          `json:"high"`
	Close      float64          `json:"close"`
	Low        float64          `json:"low"`
	Volume     float64          `json:"volume"`
}

type Ticker struct {
	TickerID   int32  `json:"ticker_id"`
	ExchangeID int32  `json:"exchange_id"`
	Name       string `json:"name"`
}
